#!/bin/bash

mkdir ~/.pamac-test
cd ~/.pamac-test

git clone git@github.com:williamcanin/pamac.git

sudo ln -s $HOME/.pamac-test/pamac /usr/local/bin/pamac-install
sudo chmod +x /usr/local/bin/pamac-install

pamac-install
